# Generated by Django 4.2.9 on 2024-01-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='air',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='gaz',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='wind',
            field=models.FloatField(default=0.0),
        ),
    ]
